theme: jekyll-theme-cayman
title: Heart Disease Prediction
description: The goal of this project is to demonstrate an end-to-end Machine Learning project through a practical problem. 
url: http://ec2-52-54-129-72.compute-1.amazonaws.com:8501/
# show_downloads: true
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
